# Set this to the root of your project when deployed:

additional_import_paths = ['assets/components']

http_path       = "/"
css_dir         = ""
sass_dir        = "scss"
images_dir      = "assets/img"
javascripts_dir = "assets/js"
fonts_dir       = "assets/fonts"

relative_assets = true

# Number of decimals after commas, useful for em accuracy
Sass::Script::Number.precision = 8


# Set the project's environment
  environment = :production
 #environment = :development

if  environment == :production
    output_style = :compressed
else
    output_style =   :expanded
    sass_options = { :debug_info => false }
end


# To enable relative paths to assets via compass helper functions. Uncomment:
relative_assets = true
line_comments   = false
color_output    = false


# Copy each sprite generated by Compass without the hash
on_sprite_saved do |filename|
    if File.exists?(filename)
        FileUtils.cp filename, filename.gsub(%r{-s[a-z0-9]{10}\.png$}, '.png')
    end
end


# Replace references to the previous sprite name in CSS by the new, hash-free sprite names
on_stylesheet_saved do |filename|
    if File.exists?(filename)
        css = File.read filename
        File.open(filename, 'w+') do |f|
            f << css.gsub(%r{-s[a-z0-9]{10}\.png}, '.png')
        end
    end

    #exec('blessc ' + css_dir + "/" + File.basename(filename) + " -f")
end

require 'autoprefixer-rails'

on_stylesheet_saved do |file|
  css = File.read(file)
  File.open(file, 'w') do |io|
    io << AutoprefixerRails.process(css)
  end
end

# Sass-globbing
require 'sass-globbing'

# Load Compass Growl
#begin
#    require "compass-growl"
#rescue LoadError
#end
